# Generated by Django 3.2.25 on 2026-03-11 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0031_merge_20260311_1147'),
        ('admin_panel', '0031_merge_20260311_1150'),
    ]

    operations = [
    ]
