# Generated by Django 3.2.25 on 2026-04-07 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_number',
        ),
        migrations.AlterField(
            model_name='customer',
            name='wave',
            field=models.CharField(choices=[('Vikas', 'Vikas'), ('Amrith', 'Amrith'), ('Samriddhi', 'Samriddhi'), ('Zayana', 'Zayana'), ('Prabhav', 'Prabhav'), ('Sexellence', 'Sexellence'), ('Aanandha', 'Aanandha'), ('Relax', 'Relax')], max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.plan'),
        ),
    ]
