# Generated by Django 3.2.25 on 2026-04-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20260407_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
