# Generated by Django 3.2.25 on 2026-04-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_slot_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='wave',
            field=models.CharField(max_length=50),
        ),
    ]
