# Generated by Django 3.2.25 on 2026-04-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customer_wave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='wave',
            field=models.CharField(choices=[('Vikas', 'Vikas'), ('Amrith', 'Amrith'), ('Samriddhi', 'Samriddhi'), ('Zayana', 'Zayana'), ('Prabhav', 'Prabhav'), ('Sexellence', 'Sexellence'), ('Aanandha', 'Aanandha'), ('Relax', 'Relax')], max_length=20),
        ),
    ]
