# Generated by Django 3.2.25 on 2026-04-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customer_wave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
