# Generated by Django 3.2.25 on 2026-04-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_slot_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='gst_percentage',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
        ),
    ]
