# Generated by Django 3.2.25 on 2026-04-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_customer_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='gst_percentage',
        ),
        migrations.AddField(
            model_name='plan',
            name='gst',
            field=models.BooleanField(default=False),
        ),
    ]
