# Generated by Django 3.2.25 on 2026-04-08 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_customer_wave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='center',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='status',
        ),
    ]
