# Generated by Django 3.2.25 on 2026-04-10 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20260408_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotbooking',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_bookings', to='user.center'),
        ),
    ]
