# Generated by Django 3.2.25 on 2026-04-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_slotbooking_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
