# Generated by Django 3.2.25 on 2026-04-17 05:13

from django.db import migrations


def populate_waves(apps, schema_editor):
    Wave = apps.get_model('user', 'Wave')
    waves_data = [
        {'id': 15, 'wave_name': 'Vikas'},
        {'id': 16, 'wave_name': 'Zayana'},
        {'id': 17, 'wave_name': 'Samriddhi'},
        {'id': 18, 'wave_name': 'Amrith'},
        {'id': 19, 'wave_name': 'Sexellence'},
        {'id': 20, 'wave_name': 'Prabhav'},
        {'id': 21, 'wave_name': 'Aanandha'},
        {'id': 23, 'wave_name': 'Relax'},
    ]
    
    for wave_data in waves_data:
        Wave.objects.get_or_create(
            id=wave_data['id'],
            defaults={'wave_name': wave_data['wave_name']}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_wave'),
    ]

    operations = [
        migrations.RunPython(populate_waves),
    ]
