# Generated by Django 3.2.25 on 2026-04-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_populate_waves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='wave',
            field=models.CharField(blank=True, choices=[('Vikas', 'Vikas'), ('Amrith', 'Amrith'), ('Samriddhi', 'Samriddhi'), ('Zayana', 'Zayana'), ('Prabhav', 'Prabhav'), ('Sexellence', 'Sexellence'), ('Aanandha', 'Aanandha'), ('Relax', 'Relax')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('branch_user', 'Branch User')], default='branch_user', max_length=20),
        ),
    ]
