# Generated by Django 3.2.25 on 2026-04-27 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20260420_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='duration_months',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
