# Generated by Django 3.2.25 on 2026-04-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_plan_duration_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='wave',
            name='external_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
