# Generated by Django 3.2.25 on 2026-04-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_populate_waves_with_external_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='duration_months',
            field=models.IntegerField(),
        ),
    ]
