# Generated by Django 3.2.25 on 2026-05-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_secondarycustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondarycustomer',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
