# Generated by Django 3.2.25 on 2026-05-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_secondarycustomer_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondarycustomer',
            name='dob_input',
            field=models.DateField(blank=True, null=True),
        ),
    ]
