# Generated by Django 3.2.25 on 2026-05-18 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_secondarycustomer_dob_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondarycustomer',
            name='dob_input',
        ),
    ]
