# Generated by Django 3.2.25 on 2026-05-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_remove_secondarycustomer_dob_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondarycustomer',
            name='wave',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
